name: Build & Deploy Astro

on:
  pull_request:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to run the workflow on'
        required: false
        default: ''
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-main:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: artifact-main
    steps:
      - name: Checkout docs-next
        uses: actions/checkout@v4

      - name: Checkout contribution repo
        uses: actions/checkout@v4
        with:
          repository: SuperOfficeDocs/contribution
          path: external-content/contribution

      - name: Checkout SuperOfficeDocs repo
        uses: actions/checkout@v4
        with:
          repository: SuperOfficeDocs/superoffice-docs
          path: external-content/superoffice-docs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Build Astro excluding API
        env:
          API_ONLY: 'false'
        run: |
          npm run build
          mkdir -p dist-out
          cp -r dist/* dist-out/

      - name: Upload main artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-main
          path: dist-out

  build-api:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: artifact-api
    steps:
      - name: Checkout docs-next
        uses: actions/checkout@v4

      - name: Checkout contribution repo
        uses: actions/checkout@v4
        with:
          repository: SuperOfficeDocs/contribution
          path: external-content/contribution

      - name: Checkout SuperOfficeDocs repo
        uses: actions/checkout@v4
        with:
          repository: SuperOfficeDocs/superoffice-docs
          path: external-content/superoffice-docs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Build Astro API only
        env:
          API_ONLY: 'true'
        run: |
          npm run build
          mkdir -p dist-out
          cp -r dist/* dist-out/

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-api
          path: dist-out

  deploy:
    needs: [build-main, build-api]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download main artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-main
          path: ./artifacts/main

      - name: Download API artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-api
          path: ./artifacts/api

      - name: Merge build outputs
        run: |
          mkdir final-dist
          cp -r artifacts/main/* final-dist/
          cp -r artifacts/api/* final-dist/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: final-dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
